extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python dce.py",
    "brili -p {args}",
]

[runs.cpf]
pipeline = [
    "bril2json",
    "python cpf.py",
    "python dce.py",
    "brili -p {args}",
]

# [runs.lvn1]
# pipeline = [
    # "bril2json",
    # "python ../lvn.py -f -c",
    # "python cpf.py",
    # "brili -p {args}",
# ]
