extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../benchmarks/core/*.bril'
# benchmarks = '../test/lvn/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python dce.py",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "python lvn.py",
    "python dce.py",
    "brili -p {args}",
]

[runs.cpf]
pipeline = [
    "bril2json",
    "python cpf.py",
    "python dce.py",
    "brili -p {args}",
]

[runs.cpf_and_lvn]
pipeline = [
    "bril2json",
    "python lvn.py",
    "python cpf.py",
    "python dce.py",
    "brili -p {args}",
]
