extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.cfg]
pipeline = [
    "bril2json",
    "python cfg.py -t",
    "brili -p {args}",
]
