extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python cpf.py",
    "python lvn.py",
    "python dce.py",
    "brili -p {args}",
]
